version: "3.9"

services:
  frontend:
    container_name: web
    image: ghcr.io/abhijeetnagar56/devtrack-frontend:latest
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=http://backend:4321/api
    depends_on:
      backend:
        condition: service_healthy

  backend:
    container_name: server
    image: ghcr.io/abhijeetnagar56/devtrack-backend:latest
    ports:
      - "4321:4321"
    environment:
      - FRONTEND_URL=http://frontend:8080
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=appdb
      - DB_USER=root
    secrets:
      - mysql_root_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      database:
        condition: service_healthy


  database:
    container_name: app_mysql2
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    secrets:
      - mysql_root_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

secrets:
  mysql_root_password:
    file: ./mysql_root_password.txt

volumes:
  mysql_data:
