
services:
  frontend:
    container_name: web
    image: devtrack
    ports:
      -8080:80

  backend:
    container_name: server
    image: app_backend
    ports:
      -4321:4321
    healthcheck:
      test: ["curl", "https://localhost:4321/api"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - serviceName


  database:
    container_name: app_mysql2
    image: mysql:8
    ports:
      -3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: value
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["psql", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    


