# User Setup non root user for safety
services:
  backend:
    build: ./backend
    user: "1000:1000"

# Dockerfile
FROM node:18
RUN useradd -m appuser
USER appuser
# Dockerfile

# File permissions to read only
services:
  frontend:
    image: nginx:1.27
    read_only: true
    volumes:
      - ./frontend/static:/usr/share/nginx/html:ro

# Secrets to insert sensitive data at the time runnnig the docker
services:
  db:
    image: postgres:16
    secrets:
      - db_password

secrets:
  db_password:
    file: ./secrets/db_password.txt
